### ISSUE TITLE
정리할 것

### ISSUE THREAD

**Issue by sang-w0o** [sang-w0o/Study#2]
# 책
- [x] MSA (<a href="http://www.yes24.com/Product/Goods/98880996">링크</a>)
- [ ] Effective Java (<a href="http://www.yes24.com/Product/Goods/65551284?OzSrank=1">링크</a>): DOING
- [ ] Kotlin in Action (<a href="http://www.yes24.com/Product/Goods/55148593?OzSrank=1">링크</a>)
- [ ] 객체지향의 사실과 오해 (<a href="http://www.yes24.com/Product/Goods/18249021">링크</a>)

# 코드 예제
- [x] Redux Saga 사용 방법
- [x] Spring: Using Feign to handle synchronous requests.
- [x] Spring: Using Kafka(producer, consumer) for event driven requests.
- [x] Lambda로 이미지 리사이징 후 S3에 업로드하기
- [x] InversifyJS 로 DI 및 IOC 적용하기
- [x] 데이터베이스 transaction isolation level

**Comment by sangwoo-98** [comment]
- [ ] RuntimeException과 Exception 차이 
- [ ] @ResponseStatus의 사용 
- [ ] @Valid, @NotBlank, @ValueOfEnum의 사용 - [ ]
